"""Reporter Agent — 팩터 근거 + 성과 리포트 Markdown 생성"""
import json, sys, os, argparse
import pandas as pd
from datetime import datetime

def main():
    parser = argparse.ArgumentParser(description="Reporter Agent")
    parser.add_argument("--run-dir", required=True, help="runs/ 결과 디렉터리")
    parser.add_argument("--signals", default=None, help="signals.csv 경로")
    parser.add_argument("--weights", default=None, help="weights.json 경로")
    args = parser.parse_args()

    run_dir = args.run_dir
    result_path = os.path.join(run_dir, "run_result.json")

    if not os.path.exists(result_path):
        print("[Reporter] run_result.json 없음", file=sys.stderr)
        sys.exit(1)

    with open(result_path) as f:
        result = json.load(f)

    # 시그널 로드
    signals = None
    if args.signals and os.path.exists(args.signals):
        signals = pd.read_csv(args.signals, dtype={"code": str}, index_col="code")

    # 비중 로드
    weights = {}
    if args.weights and os.path.exists(args.weights):
        with open(args.weights) as f:
            weights = json.load(f)

    # Markdown 생성
    m = result.get("metrics", {})
    wf = result.get("walk_forward", {})
    lines = [
        f"# Quant Report: {result.get('strategy', 'unknown')}",
        f"생성: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## 성과 요약",
        "",
        "| 지표 | 값 |",
        "|------|------|",
        f"| CAGR | {m.get('cagr', 0):.2%} |",
        f"| Sharpe | {m.get('sharpe', 0):.2f} |",
        f"| Sortino | {m.get('sortino', 0):.2f} |",
        f"| MDD | {m.get('mdd', 0):.2%} |",
        f"| Win Rate | {m.get('win_rate', 0):.1%} |",
        f"| Profit Factor | {m.get('profit_factor', 0):.2f} |",
        "",
    ]

    # Walk-forward
    if wf:
        is_m = wf.get("in_sample", {})
        oos_m = wf.get("out_of_sample", {})
        lines += [
            "## Walk-Forward 검증",
            "",
            "| 구간 | Sharpe | CAGR | MDD |",
            "|------|--------|------|-----|",
            f"| In-Sample (70%) | {is_m.get('sharpe', 0):.2f} | {is_m.get('cagr', 0):.2%} | {is_m.get('mdd', 0):.2%} |",
            f"| Out-of-Sample (30%) | {oos_m.get('sharpe', 0):.2f} | {oos_m.get('cagr', 0):.2%} | {oos_m.get('mdd', 0):.2%} |",
            "",
        ]
        if "warning" in wf:
            lines.append(f"> **경고**: {wf['warning']}")
            lines.append("")

    # 편입 종목 + 팩터 근거
    if weights and signals is not None and not signals.empty:
        lines += ["## 편입 종목 (팩터 근거)", ""]
        header = "| 종목 | 비중 |"
        sep = "|------|------|"
        factor_cols = [c for c in signals.columns if c not in ("composite_score", "rank")]
        if factor_cols:
            header += " " + " | ".join(f"{c}" for c in factor_cols) + " |"
            sep += " " + " | ".join("------" for _ in factor_cols) + " |"
        lines += [header, sep]

        for code in sorted(weights, key=lambda c: -weights[c]):
            row = f"| {code} | {weights[code]:.1%} |"
            if code in signals.index and factor_cols:
                for c in factor_cols:
                    v = signals.loc[code, c] if c in signals.columns else 0
                    row += f" {v:.0f} |"
            lines.append(row)
        lines.append("")
    elif weights:
        lines += ["## 편입 종목", ""]
        for code, w in sorted(weights.items(), key=lambda x: -x[1]):
            lines.append(f"- {code}: {w:.1%}")
        lines.append("")

    # 비용 모델
    cost = result.get("cost_model", {})
    lines += [
        "## 비용 모델",
        f"- 수수료: {cost.get('fee_bps', 0)} bps",
        f"- 슬리피지: {cost.get('slippage_bps', 0)} bps",
        "",
        "---",
        "*Generated by InvestQuant Pipeline*",
    ]

    report = "\n".join(lines)
    out_path = os.path.join(run_dir, "report.md")
    with open(out_path, "w") as f:
        f.write(report)
    print(f"[Reporter] 리포트 생성: {out_path}")

if __name__ == "__main__":
    main()
